[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
IterativeSolvers = ">=0.8.5"
LinearAlgebra = ">=1.12.0"
julia = "1.1.0"
