[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"

[compat]
ForwardDiff = ">=0.10.39"
Optimization = ">=3.19.3"
OptimizationOptimJL = ">=0.1.14"
julia = "1.6.0"
