[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatrixColorings = "0a514795-09f3-496d-8182-132a7b665d35"

[compat]
SparseArrays = ">=1.12.0"
SparseMatrixColorings = ">=0.4.6"
julia = "1.6.0"
